u-boot-ingenic: add sdstart command and feature
OpenIPC/u-boot-ingenic pull request #3
Opened 2023-10-15 11:01 UTC by gtxaspec

u-boot-ingenic: Introduce the 'sdstart' Command for Flexible Kernel Booting

This update brings the 'sdstart' command to u-boot, mirroring a feature found in the factory version of u-boot. It  allows users to boot from a custom kernel without necessitating a permanent flash to the device.   This aids in debugging and development of OpenIPC.

For this to work, users should place a uniquely named kernel, `factory_0P3N1PC_kernel`, at the root of their MMC card. Upon boot, the device will load and boot using this specified kernel.   Users are also able to manually invoke the 'sdstart' command on the u-boot command line.  You may also manually cancel the loading of the kernel by pressing 'ctrl-c' during the loading prompt.  

The deliberate choice of a distinct kernel name aligns with the factory method, ensuring the kernel is loaded purely on user intent, preventing accidental booting.

Tested on: 

T20:
WyzeCam v2
WyzeCam v2 black

T31:
Wyze Pan  V2
Wyze V3
Wyze Doorbell3
AtomCam 2

2023-10-15 16:36 UTC, FlyRouter requested changes
Thanks for the PR, however the idea needs further discussion
Please see an example of how it is done in other situations, such as the "bootnfs" command. In the simplest case it is enough to change 10 characters in bootcmd, from "sf read" to "fatload".
Also don't forget that U-Boot can read scripts from SD card.

2023-10-15 18:34 UTC, FlyRouter commented
https://github.com/geomatsi/e-notes/blob/master/u-boot-script.txt

2023-10-16 01:36 UTC, gtxaspec commented
Hi @FlyRouter,

I genuinely appreciate your insights and the valuable resources you've shared. While I'm well-versed with the scripting and environment loading capabilities of our U-Boot version for the Ingenic platform, there are crucial reasons for integrating the code directly into U-Boot:

Our U-Boot version doesn't support the scripting functionality, specifically the CONFIG_HUSH_PARSER. Enabling this would enlarge the U-Boot binary to a size that the mtd0 partition exceeds within the OpenIPC environment.  This feature would be required this to support scripting, enabling support of the multitude of memory configurations that exist between the different Ingenic platform CPU's.

Loading the kernel from the MMC also poses some challenges with the existing OpenIPC U-Boot configuration:

Currently, the command mmc=mmc rescan;mw.b 0x80600000 0xff 0xFFFC;load mmc 0:1 0x80600000 uenv-openipc.txt;env import -t 0x80600000 ${filesize};saveenv loads the uenv-openipc.txt. This process overwrites the existing configuration and saves it to flash, leading to a permanent modification. Moreover, as indicated by your example from https://raw.githubusercontent.com/geomatsi/e-notes/master/u-boot-script.txt, boot scripts (boot.scr) aren't operational in the existing OpenIPC U-Boot setup.

With this PR, we aim to provide seamless and fully functional support across all Ingenic platforms that OpenIPC currently supports.

Let me know what you think! Thank You =D

2023-10-16 08:40 UTC, gtxaspec commented
I also understand we currently support nfsboot via uboot.  Though on many devices, specifically Wyze, AtomCam, and other vendors which do not have ethernet, devices which are **WiFi only**, these additions also contribute to testing and use of these devices.

2023-10-17 09:26 UTC, FlyRouter approved these changes
Thank you

2023-10-17 11:15 UTC, gtxaspec commented
@FlyRouter ready to be merged  =D thank you.

2023-10-17 17:19 UTC, p0i5k commented
What `factory_0P3N1PC_kernel` does mean? Why not `uImage`?

2023-10-17 19:28 UTC, gtxaspec commented
@p0i5k The deliberate choice of a distinct kernel name aligns with the factory method used by some of the device vendors, ensuring the kernel is loaded purely on user intent, preventing accidental booting.

2023-11-05 04:07 UTC, archandanime commented
I made a program [here](https://github.com/archandanime/wz_flash-helper) that makes use of this PR with `sdstart` functionality. It allows backup/restore partitions in both stock and OpenIPC, it also allows switching between stock and OpenIPC and setup initial uboot `env` variables.
I really hope this PR is merged!

2023-11-05 21:23 UTC, ZigFisher commented
Please expect, we will make a decision as soon as possible.
Thank you all for your work, gentlemen.

2024-01-18 05:22 UTC, closed without merging